### PR TITLE
Fix for Issue #7

### PR DESCRIPTION
**Pull request by vasilich6107**
Hi @johynpapin could you check the PR

### CODE REVIEW

**Comment by ghost** [comment]
Hi! Thank you very much for this PR! :pray:

I will check it as soon as I can!

**Comment by ghost** [comment]
Hello !

Sorry for the wait, I was traveling. Thanks a lot for this contribution, I did some tests and everything seems to work on my side!

To be very honest I don't really remember why I chose `srcIn`. I will try to understand this code better later.

I will publish a new version! :tada:

**Comment by vasilich6107** [comment]
Hi @johynpapin 
Please be aware that there is an issue for impeller
https://github.com/flutter/flutter/issues/127232

It is considered as a bug
But maybe makes sense to bump package to v2 to omit auto updates

**Comment by ghost** [comment]
Thank you so much for opening this issue @vasilich6107! :pray:

The bug is present on the current version too, right? (#4)

**Comment by vasilich6107** [comment]
@johynpapin it seems that there is no bug for `srcIn` case.
Only for `src`

**Comment by ghost** [comment]
OK, I will follow your advice then!

**Pull request merged**
